version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./../postgres_volumes:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 && ./docker_entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db