# Generated by Django 2.2.10 on 2020-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20200523_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ManyToManyField(to='album.Category'),
        ),
    ]
