# Generated by Django 2.2.10 on 2020-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_album_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
