# Generated by Django 2.2.10 on 2020-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_category_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
